//! SQL contract for the owned library. JSON is used for variable model recipes, not indexes.

pub const SCHEMA: &str = r#"
PRAGMA foreign_keys = ON;
PRAGMA journal_mode = WAL;
PRAGMA synchronous = FULL;
CREATE TABLE IF NOT EXISTS history (
    id TEXT PRIMARY KEY,
    created_at INTEGER NOT NULL,
    status TEXT NOT NULL,
    payload TEXT NOT NULL CHECK(json_valid(payload))
);
CREATE INDEX IF NOT EXISTS history_date ON history(created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS history_status ON history(status);
CREATE TABLE IF NOT EXISTS assets (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    width INTEGER NOT NULL CHECK(width > 0),
    height INTEGER NOT NULL CHECK(height > 0),
    mime TEXT NOT NULL,
    source TEXT NOT NULL CHECK(source IN ('file','clipboard','url','generated')),
    history_id TEXT,
    model TEXT,
    provider TEXT,
    prompt TEXT NOT NULL DEFAULT '',
    details_json TEXT CHECK(details_json IS NULL OR json_valid(details_json)),
    byte_size INTEGER NOT NULL CHECK(byte_size >= 0),
    favorite INTEGER NOT NULL DEFAULT 0 CHECK(favorite IN (0,1)),
    pending_delete INTEGER NOT NULL DEFAULT 0 CHECK(pending_delete IN (0,1)),
    availability TEXT NOT NULL DEFAULT 'available' CHECK(availability IN ('available','missing')),
    search_text TEXT NOT NULL,
    thumbnail BLOB,
    thumbnail_revision INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS assets_date ON assets(created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS assets_model_date ON assets(model, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS assets_source_date ON assets(source, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS assets_favorite_date ON assets(favorite, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS assets_availability ON assets(availability, pending_delete);
CREATE TABLE IF NOT EXISTS asset_tags (
    asset_id TEXT NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
    tag TEXT NOT NULL CHECK(length(tag) BETWEEN 1 AND 64),
    PRIMARY KEY(asset_id, tag)
);
CREATE INDEX IF NOT EXISTS asset_tags_name ON asset_tags(tag, asset_id);
-- No asset FK: deleted outputs retain their identity and cannot be regenerated by a retry.
CREATE TABLE IF NOT EXISTS generated_keys (
    generation_key TEXT PRIMARY KEY,
    asset_id TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS history_outputs (
    history_id TEXT NOT NULL REFERENCES history(id) ON DELETE CASCADE,
    ordinal INTEGER NOT NULL CHECK(ordinal >= 0),
    asset_id TEXT NOT NULL,
    PRIMARY KEY(history_id, ordinal),
    UNIQUE(history_id, asset_id)
);
CREATE TABLE IF NOT EXISTS workspace (
    id INTEGER PRIMARY KEY CHECK(id = 1),
    payload TEXT NOT NULL CHECK(json_valid(payload))
);
CREATE TABLE IF NOT EXISTS library_meta (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
PRAGMA user_version = 1;
"#;

pub const ASSET_COLUMNS: &str = r#"
a.id, a.name, a.created_at, a.width, a.height, a.mime, a.source,
a.history_id, a.model, a.provider, a.prompt, a.details_json, a.byte_size,
a.favorite, a.pending_delete, a.availability, a.thumbnail_revision,
(a.thumbnail IS NOT NULL) AS has_thumbnail,
COALESCE((SELECT json_group_array(t.tag) FROM
    (SELECT tag FROM asset_tags WHERE asset_id = a.id ORDER BY tag) t), '[]') AS tags_json
"#;

// Bind in order: normalized search, source, model, normalized tag, fromMs inclusive,
// untilMs exclusive, optional favorite, availability. Count and page MUST share this clause.
pub const ASSET_FILTER: &str = r#"
FROM assets a
WHERE (?1 = '' OR instr(a.search_text, ?1) > 0 OR EXISTS (
    SELECT 1 FROM asset_tags t WHERE t.asset_id = a.id AND instr(t.tag, ?1) > 0
))
AND (?2 = 'all' OR (?2 = 'imported' AND a.source <> 'generated') OR a.source = ?2)
AND (?3 IS NULL OR a.model = ?3)
AND (?4 IS NULL OR EXISTS (SELECT 1 FROM asset_tags t WHERE t.asset_id = a.id AND t.tag = ?4))
AND (?5 IS NULL OR a.created_at >= ?5)
AND (?6 IS NULL OR a.created_at < ?6)
AND (?7 IS NULL OR a.favorite = ?7)
AND (?8 = 'all'
    OR (?8 = 'pending' AND a.pending_delete = 1)
    OR (?8 IN ('available','missing') AND a.pending_delete = 0 AND a.availability = ?8))
"#;

pub const ORDER_NEWEST: &str = " ORDER BY a.created_at DESC, a.id DESC";
pub const ORDER_OLDEST: &str = " ORDER BY a.created_at ASC, a.id ASC";
pub const ORDER_NAME: &str = " ORDER BY a.name COLLATE NOCASE ASC, a.id ASC";
pub const ORDER_SIZE: &str = " ORDER BY a.byte_size DESC, a.id DESC";
pub const PAGE: &str = " LIMIT ?9 OFFSET ?10";
pub const ASSET_BY_ID: &str = " FROM assets a WHERE a.id = ?1";
pub const ALL_ASSETS: &str = " FROM assets a ORDER BY a.created_at DESC, a.id DESC";
pub const TAGS: &str = "SELECT DISTINCT tag FROM asset_tags ORDER BY tag";
pub const MODELS: &str = "SELECT DISTINCT model FROM assets WHERE model IS NOT NULL ORDER BY model";
pub const THUMBNAIL: &str =
    "SELECT thumbnail FROM assets WHERE id = ?1 AND pending_delete = 0";
pub const GENERATION_KEY: &str =
    "SELECT asset_id FROM generated_keys WHERE generation_key = ?1";
pub const INSERT_GENERATION_KEY: &str =
    "INSERT INTO generated_keys(generation_key, asset_id) VALUES (?1, ?2)";
pub const INSERT_ASSET: &str = r#"
INSERT INTO assets(
    id, name, created_at, width, height, mime, source, history_id, model, provider,
    prompt, details_json, byte_size, search_text, thumbnail
) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14,?15)
"#;
pub const RENAME: &str =
    "UPDATE assets SET name = ?2, search_text = ?3 WHERE id = ?1 AND pending_delete = 0";
pub const FAVORITE: &str =
    "UPDATE assets SET favorite = ?2 WHERE id = ?1 AND pending_delete = 0";
pub const ADD_TAG: &str = "INSERT OR IGNORE INTO asset_tags(asset_id, tag) VALUES (?1, ?2)";
pub const REMOVE_TAG: &str = "DELETE FROM asset_tags WHERE asset_id = ?1 AND tag = ?2";
pub const MARK_DELETE: &str = "UPDATE assets SET pending_delete = 1 WHERE id = ?1";
pub const DELETE_ASSET: &str = "DELETE FROM assets WHERE id = ?1";
pub const PENDING_IDS: &str = "SELECT id FROM assets WHERE pending_delete = 1 ORDER BY id";
pub const MISSING_IDS: &str =
    "SELECT id FROM assets WHERE availability = 'missing' AND pending_delete = 0 ORDER BY id";
pub const MARK_MISSING: &str =
    "UPDATE assets SET availability = 'missing' WHERE id = ?1 AND pending_delete = 0";
pub const MARK_AVAILABLE: &str =
    "UPDATE assets SET availability = 'available', byte_size = ?2 WHERE id = ?1 AND pending_delete = 0";
pub const SET_THUMBNAIL: &str = r#"
UPDATE assets SET thumbnail = ?2, thumbnail_revision = thumbnail_revision + 1
WHERE id = ?1 AND pending_delete = 0
"#;

pub const HISTORY_ALL: &str = "SELECT payload FROM history ORDER BY created_at DESC, id DESC";
pub const HISTORY_RUNNING: &str = "SELECT payload FROM history WHERE status = 'running'";
pub const HISTORY_ONE: &str = "SELECT payload FROM history WHERE id = ?1";
pub const HISTORY_ACTIVE: &str =
    "SELECT EXISTS(SELECT 1 FROM history WHERE status IN ('queued','running'))";
pub const SAVE_HISTORY: &str = r#"
INSERT INTO history(id, created_at, status, payload) VALUES (?1, ?2, ?3, ?4)
ON CONFLICT(id) DO UPDATE SET created_at = excluded.created_at,
status = excluded.status, payload = excluded.payload
"#;
pub const DELETE_HISTORY: &str = "DELETE FROM history WHERE id = ?1";
pub const HISTORY_OUTPUTS: &str =
    "SELECT asset_id FROM history_outputs WHERE history_id = ?1 ORDER BY ordinal";
pub const ADD_HISTORY_OUTPUT: &str = r#"
INSERT OR IGNORE INTO history_outputs(history_id, ordinal, asset_id)
SELECT ?1, COALESCE(MAX(ordinal) + 1, 0), ?2 FROM history_outputs WHERE history_id = ?1
"#;
pub const HISTORY_PROGRESS: &str = r#"
UPDATE history SET payload = CASE WHEN ?3 IS NULL
    THEN json_set(payload, '$.phase', ?2)
    ELSE json_set(payload, '$.phase', ?2, '$.taskId', ?3) END
WHERE id = ?1 AND status = 'running'
"#;
pub const LOAD_WORKSPACE: &str = "SELECT payload FROM workspace WHERE id = 1";
pub const SAVE_WORKSPACE: &str = r#"
INSERT INTO workspace(id, payload) VALUES (1, ?1)
ON CONFLICT(id) DO UPDATE SET payload = excluded.payload
"#;
// Counts describe registered non-deleted assets; original bytes exclude known missing files.
// Database bytes (including WAL/SHM) are obtained separately from filesystem metadata.
pub const STATS: &str = r#"
SELECT
    COUNT(CASE WHEN pending_delete = 0 THEN 1 END) AS total_count,
    COUNT(CASE WHEN pending_delete = 0 AND availability = 'missing' THEN 1 END) AS missing_count,
    COUNT(CASE WHEN pending_delete = 0 AND favorite = 1 THEN 1 END) AS favorite_count,
    COUNT(CASE WHEN pending_delete = 1 THEN 1 END) AS pending_delete_count,
    COALESCE(SUM(CASE WHEN pending_delete = 0 AND availability = 'available' THEN byte_size ELSE 0 END), 0) AS original_bytes,
    COALESCE(SUM(length(thumbnail)), 0) AS thumbnail_bytes,
    (SELECT COUNT(*) FROM history) AS history_count,
    (SELECT value FROM library_meta WHERE key = 'last_checked_at') AS last_checked_at
FROM assets
"#;
pub const SET_CHECKED: &str = r#"
INSERT INTO library_meta(key, value) VALUES ('last_checked_at', ?1)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
"#;
pub const QUICK_CHECK: &str = "PRAGMA quick_check";
